(function () {
  const e = React.createElement;

  const HOME_HTML = `
<section class="content">
  <img src="/assets/img/logo ods.png" alt="Logo ODS" class="logo" loading="lazy">
  <img src="/assets/img/logo.png" alt="Logo PROCONSVATE" class="logoproject logo--livre" loading="lazy">
  <p>Preservar a vida aquática e terrestre é essencial para manter o equilíbrio do nosso ambiente. Temos a responsabilidade de adotar práticas sustentáveis que protejam os habitats e garantam a sobrevivência das espécies. Este programa busca sensibilizar sobre a importância de ações que ajudem a conservar o meio ambiente, ressaltando a necessidade de um enfoque integrado para a vida tanto na Terra quanto na água.</p>
  <p>A proteção da vida aquática e terrestre é crucial para garantir um futuro sustentável. A diversidade biológica nos oceanos, rios, florestas e savanas desempenha um papel fundamental no equilíbrio ambiental global. Cada espécie, desde plânctons até microrganismos do solo, tem um papel específico na complexa rede da vida. Precisamos preservar esses ecossistemas, reduzir a poluição e promover o uso responsável dos recursos naturais.</p>
</section>
<section class="content"><figure><img src="/assets/img/agua.png" alt="Vida Aquática" class="image-right image-fix" loading="lazy" width="400"><figcaption style="margin-left: auto; text-align: right; width: fit-content;">Gerado por IA</figcaption></figure><p>A vida aquática, que varia de pequenos plânctons a grandes baleias, é crucial para a saúde dos oceanos e para a produção de oxigênio. Esses organismos sustentam ecossistemas marinhos complexos e são vitais para o equilíbrio ambiental. Rios e lagos também fornecem água doce essencial para a sobrevivência humana e para o desenvolvimento de comunidades ao redor do mundo. Proteger esses recursos é fundamental para garantir a continuidade da vida em nosso planeta. A preservação da biodiversidade marinha e a qualidade da água doce são essenciais para nossa sobrevivência e para a saúde global do planeta. Conscientizar e se comprometer com a conservação é fundamental para assegurar um futuro sustentável.</p><blockquote>"A natureza não é um lugar para visitar. Ela é o lar." – Gary Snyder</blockquote></section>
<section class="content"><figure><img src="/assets/img/vida terrestre.avif" class="image-left" alt="Vida Terrestre" loading="lazy" width="400"><figcaption>Fonte: https://shre.ink/qahc</figcaption></figure><p>Florestas e savanas são essenciais para a vida na Terra, desempenhando papéis vitais na saúde ambiental e na qualidade de vida. Esses ecossistemas abrigam uma imensa biodiversidade, sustentando inúmeras espécies de plantas e animais. Além de seu valor ecológico, eles ajudam a regular o clima, controlar as temperaturas e sequestrar carbono da atmosfera. Também são fundamentais na purificação do ar e da água. Preservar esses habitats é crucial para proteger a biodiversidade, garantir a saúde do nosso planeta e o bem-estar das futuras gerações. A conservação dessas áreas naturais é um compromisso vital para a sustentabilidade e qualidade de vida global.</p><blockquote>"O que fazemos com as florestas do mundo é apenas um espelho do que fazemos a nós mesmos e uns aos outros." – Mahatma Gandhi</blockquote></section>
<section class="content"><figure><img src="/assets/img/preservação.webp" class="image-right" alt="Preservação" loading="lazy" width="400"><figcaption style="text-align: right;">Fonte: https://shre.ink/qahQ</figcaption></figure><p>A poluição dos mares e o desmatamento são problemas urgentes que precisam de nossa atenção constante. A poluição marinha, principalmente pelo descarte inadequado de plásticos, está devastando habitats e afetando a vida marinha. O desmatamento, por sua vez, causa perda de biodiversidade e altera os ciclos climáticos. Precisamos reduzir o uso de plásticos descartáveis e adotar práticas de consumo mais sustentáveis. A reciclagem, a escolha de produtos com menos embalagens e a busca por alternativas ecológicas são passos importantes para preservar nossos ambientes naturais e proteger os recursos que sustentam a vida. Ao agir de forma consciente, podemos enfrentar esses desafios e garantir um futuro mais saudável para o planeta.</p><blockquote>"Não herdamos a Terra de nossos ancestrais, a tomamos emprestada de nossos filhos." – Provérbio nativo americano</blockquote></section>
<section class="content"><figure><img src="/assets/img/conciência.jpg" alt="Consciência Ambiental" class="image-left" loading="lazy" width="400"><figcaption style="margin-right: auto; text-align: left; width: fit-content;">Gerado por IA</figcaption></figure><p>Ensinar as novas gerações sobre a importância da conservação é essencial para um futuro mais verde e sustentável. Ao compartilhar conhecimentos e valores sobre o cuidado com o meio ambiente, estamos preparando os jovens para tomar decisões mais conscientes e responsáveis. As escolhas que fazemos hoje moldam o futuro do planeta. Investir em educação ambiental ajuda a entender melhor os desafios e inspira um compromisso com a proteção dos recursos naturais. Cultivar um respeito profundo pelo meio ambiente é fundamental para construir um futuro onde a harmonia entre seres humanos e natureza seja duradoura.</p><blockquote>"A educação é a arma mais poderosa que você pode usar para mudar o mundo." – Nelson Mandela</blockquote></section>
<section class="content"><figure><img src="/assets/img/Terra.jpg" alt="Sustentabilidade" class="image-right image-terra--fix" loading="lazy" width="400"><figcaption style="margin-left: auto; text-align: right; width: fit-content;">Gerado por IA</figcaption></figure><p>A sustentabilidade é uma necessidade urgente e não pode ser adiada. Precisamos repensar nossos hábitos de consumo e estilo de vida, adotando práticas mais conscientes e responsáveis desde agora. Só assim poderemos assegurar que a vida na Terra continue a prosperar e que as próximas gerações tenham um futuro saudável e equilibrado.</p><blockquote>"A Terra fornece o suficiente para satisfazer as necessidades de todos os homens, mas não a ganância de todos os homens." – Mahatma Gandhi</blockquote></section>
<section class="content objective-awareness"><h2>Nosso Objetivo</h2><p>Nosso objetivo é aumentar a conscientização global sobre a importância de preservar a vida aquática e terrestre, destacando os desafios que ameaçam a biodiversidade e as soluções que podemos adotar. Queremos estimular a adoção de práticas sustentáveis que protejam os ecossistemas e assegurem um futuro saudável para todas as formas de vida.</p><h2>Conscientização</h2><p>A conscientização é o primeiro passo para a mudança. Compreender os impactos de nossas ações no meio ambiente permite que tomemos decisões mais informadas e responsáveis. Preservar a vida na Terra e na água depende de todos nós, e pequenas mudanças em nosso cotidiano podem gerar grandes resultados.</p><h3>Um Pouco deste Projeto</h3><p>Este Projeto Utiliza-se de 2 ODS dentre as 17 ODS, a ODS 14 e a ODS 15, que ajudam a preservar a vida terrestre e aquática, respectivamente.</p></section>`;

  const PROCONSVATE_HTML = `<h1 class="h1 pro">Quem Somos Nós?</h1><img src="/assets/img/logo.png" alt="Logo PROCONSVATE" class="logoproject logo--livre pro" loading="lazy"><p class="p pro"> A <strong>"PROCONSVATE"</strong> é um Programa de Conscientização Ambiental, criado em 2024, que busca promover a conscientização global sobre a importância de preservar a vida aquática e terrestre. Juntamente com a ODS 14 e a ODS 15, que ajudam a preservar a vida terrestre e aquática, respectivamente. Devemos tomar a responsabilidade de adotar práticas sustentáticas que protejam os habitats e garantam a sobrevivência das espécies. Cada espécie, desde plânctons até microrganismos do solo, tem um papel específico na complexa rede da vida. Hoje em dia muitas especies correm risco de extinção, e muitos habitats estao sendo degradados pela poluicao e uso irresponsavel dos recursos naturais. A sua e nossa participação na preservação da vida terrestre e aquática e importante para garantir a sustentabilidade do nosso planeta. Compreender os impactos de nossas ações no meio ambiente permite que tomemos decisões mais informadas e responsáveis. Preservar a vida na Terra e na água depende de todos nós, e pequenas mudanças em nosso cotidiano podem gerar grandes resultados. Caso queira saber mais sobre a importância de preservar a vida terrestre e aquática, visite nossa pagina de conscientização, clicando no botão Inicio acima. Qualquer Denúncia de maus tratos com animais, sendo terrestres ou aquáticos, contate o IBAMA - Telefone (Linha Verde): <a class="ibama" href="tel:0800618080">0800 61 8080</a><br><span><br><strong>Toda ação ajuda, faça sua parte.</strong></span></p>`;

  function layout(main, options = {}) {
    const headerClass = options.headerClass || "";
    return e(React.Fragment, null,
      e("div", { id: "topo" }),
      e("header", { className: `site-header ${headerClass}`.trim(), role: "banner" },
        e("div", { className: `container header-inner ${headerClass}`.trim() },
          e("a", { className: "brand", href: "/", "aria-label": "Início PROCONSVATE" }, "PROCONSVATE"),
          e("img", { className: "logo-float", src: "/assets/img/logo.png", width: 48, height: 48, alt: "Logo PROCONSVATE", "aria-hidden": true, loading: "lazy" }),
          e("nav", { id: "menu-principal", className: "site-nav", "aria-label": "Menu principal" },
            e("ul", null,
              e("li", null, e("a", { href: "/", className: "active button1" }, "Início")),
              e("li", null, e("a", { href: "/noticias", className: "active button2" }, "Notícias")),
              e("li", null, e("a", { href: "/quiz", className: "active button3" }, "Quiz")),
              e("li", null, e("a", { href: "/sobre", className: "active button4" }, "Sobre"))
            )
          )
        )
      ),
      main,
      e("footer", { className: `site-footer ${options.about ? "sobre" : ""}`.trim(), role: "contentinfo" },
        e("div", { className: "container" },
          e("p", null, e("strong", null, "Programa de Conscientização de Vida Aquática e Terrestre (PROCONSVATE)")),
          e("p", null, "Matheus Antunes Reis © Todos os direitos reservados - Desenvolvido por MR SISTEMAS"),
          e("div", { className: "back-to-top-wrapper" }, e("a", { className: "back-to-top", href: "#topo" }, "Voltar ao topo"))
        ),
        !options.about && e("a", { href: "https://wa.me/5538988064942", className: "number-phone btn-float", target: "_blank", rel: "noopener" }, e("i", { className: "fa-brands fa-whatsapp" })),
        e("a", { href: "https://www.instagram.com/proconsvate?igsh=MWMwb3ZucWFydmFyMQ==", className: "insta-btn", target: "_blank", rel: "noopener" }, e("img", { src: "/assets/img/insta.png", alt: "Instagram", loading: "lazy" })),
        e("p", { className: "insta-text" }, "Siga-nos no Instagram!"),
        e("p", { className: "email-text" }, "proconsvate@gmail.com")
      )
    );
  }

  function App() {
    const path = window.location.pathname.replace(/\/$/, "") || "/";
    if (path === "/noticias") return layout(e("main", { id: "conteudo-principal", tabIndex: "-1", className: "site-main", role: "main" }, e("iframe", { src: "https://www.cnnbrasil.com.br/tudo-sobre/animais/", id: "product-frame", title: "Lista de notícias sobre animais da CNN Brasil", className: "noticas" })));
    if (path === "/quiz") return layout(e("main", { id: "conteudo-principal", tabIndex: "-1", className: "site-main", role: "main" }, e("h1", { style: { textAlign: "center", textDecoration: "none", filter: "drop-shadow(1px 8px 8px black)" } }, 'Ao clicar em Jogar o Quiz, clique em "continuar sem login" '), e("iframe", { src: "https://pt.quizur.com/trivia/como-esta-sua-consciencia-ambiental-teste-aqui-1pLTa", id: "product-frame", title: "Quiz: Você é consciente ambiental?", className: "quiz" })));
    if (path === "/proconsvate") return layout(e("main", { id: "conteudo-principal", tabIndex: "-1", className: "site-main pro", role: "main", dangerouslySetInnerHTML: { __html: PROCONSVATE_HTML } }), { headerClass: "pro" });
    if (path === "/sobre") return layout(e("main", { id: "conteudo-principal", tabIndex: "-1", className: "site-main", role: "main" }, e("img", { src: "/assets/img/logo.png", alt: "Logo PROCONSVATE", className: "logoproject logo--livre sobre", loading: "lazy" }), e("div", { className: "PROCONSVATE" }, e("h1", null, "PROCONSVATE (Programa de Conscientização de Vida Aquática e Terrestre)")), e("button", { className: "chat-launcher", "aria-label": "Abrir chat", id:"launcher" }, "💬"), e("div", { className:"chat", id:"chat", role:"dialog", "aria-label":"Sobre o Projeto Proconsvate", "aria-modal":false }, e("header", {className:"chat-header"}, e("strong", null, "Sobre o Projeto Proconsvate"), e("button", {className:"chat-close", id:"close", "aria-label":"Fechar"}, "×")), e("div", {className:"messages", id:"messages", "aria-live":"polite", "aria-atomic":false}), e("div", {className:"quick", id:"quick"}), e("div", {className:"footer", id:"footer"}, e("input", {id:"input", type:"text", placeholder:"Digite seu feedback...", autoComplete:"off"}), e("button", {id:"send"}, "Enviar"))), e("div", { style: { height: "500px" } })), { headerClass: "sobre", about: true });
    return layout(e("main", { id: "conteudo-principal", tabIndex: "-1", className: "site-main", role: "main" }, e("div", { className: "PROCONSVATE" }, e("h1", null, "PROCONSVATE (Programa de Conscientização de Vida Aquática e Terrestre)")), e("div", { dangerouslySetInnerHTML: { __html: HOME_HTML } })));
  }

  ReactDOM.createRoot(document.getElementById("root")).render(e(App));
})();
